// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVmAJtcVif2cuOIUZLXbJ0qRkeD5chqE',
    appId: '1:544755421444:android:47bff696e5d05de76ac051',
    messagingSenderId: '544755421444',
    projectId: 'redesocialpoo2025',
    storageBucket: 'redesocialpoo2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Z_MgJ_p7Uq7MW53SP-pFQJA1gjOfMVc',
    appId: '1:544755421444:web:09bdb0f31dc7db856ac051',
    messagingSenderId: '544755421444',
    projectId: 'redesocialpoo2025',
    authDomain: 'redesocialpoo2025.firebaseapp.com',
    storageBucket: 'redesocialpoo2025.firebasestorage.app',
    measurementId: 'G-B8F6GSSVNW',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Z_MgJ_p7Uq7MW53SP-pFQJA1gjOfMVc',
    appId: '1:544755421444:web:09bdb0f31dc7db856ac051',
    messagingSenderId: '544755421444',
    projectId: 'redesocialpoo2025',
    authDomain: 'redesocialpoo2025.firebaseapp.com',
    storageBucket: 'redesocialpoo2025.firebasestorage.app',
    measurementId: 'G-B8F6GSSVNW',
  );

}